### PR TITLE
Update plugins to new API

### PR DESCRIPTION
**Pull request by schulle4u**

### CODE REVIEW

**Comment by markseu** [comment]
I am sorry, we have to delay extensions for a few days. There's one more API update coming.

**Comment by schulle4u** [comment]
No problem, I'm not in a hurry. :)

**Comment by markseu** [comment]
Please try again with latest developer kit. The release command should automatically update your `extension.ini` files to the new format, you don't need to edit them. I suggest to use fresh `version.ini` and `waffle.ini` files, with your extensions added to the end.

**Comment by schulle4u** [comment]
Thanks for the hint, all extensions should be updated now.

**Comment by markseu** [comment]
Icecast and Radioboss are not included in this pull request, is this correct?

**Comment by schulle4u** [comment]
Yes, I've excluded them for now. The Icecast extension still needs some testing. Radioboss should be stable, but as it requires a special service I wasn't sure if this is relevant for the extensions repository.

**Comment by markseu** [comment]
Thank you

**Pull request merged**
