### PR TITLE
Added Karlskrona theme

### PR DESCRIPTION
**Pull request by pftnhr**

### CODE REVIEW

**Comment by annaesvensson** [comment]
@schulle4u are you available for a review?

**Comment by schulle4u** [comment]
Currently waiting for a conference meeting, I'll be up for review later this afternoon.

**Comment by schulle4u** [comment]
Thanks for submitting a new theme! Before we can accept your contribution, here are some friendly hints to improve your submission: 🙂

* The description in your installation settings and the one provided in your documentation should not differ. Use the same, concise sentence to describe your project in every place. A more detailed description can be written as separate chapters in your documentation if needed. 
  - The fact that your theme uses `pico.css` is less important for the description and already is written in the acknowledgement section. 
* Delete the file `karlskrona.js` as it contains nothing but a comment. If your theme doesn't use it by default, It is up to the user to create this file. Yellows theme system will automatically look for this file and load javascript ressources, should someone need them. 
* Use spaces instead of tabs in your code. As for the layout files I suggest to simply remove all indentations, this will bring it in sync with our general layout coding. 
* Not sure about code standard relevance, but we usually put the extension comment line (first line in `karlskrona.php`) also in the theme's css. 
* Your theme appears to cause a small issue with the edit extension. Se [my comment in this discussion](https://github.com/datenstrom/yellow/discussions/901#discussioncomment-7034424). 

This is all I have for the moment. Just let me know if something still needs clarification. 🙂

**Comment by pftnhr** [comment]
Changes made according to your comment, except for the last point, as this is probably a bug. See my bug report: https://github.com/datenstrom/yellow/discussions/902.

**Comment by schulle4u** [comment]
Some more things I previously overlooked, thanks to my helpful review assistant: 

1. In file karlskrona.php there is a leftover function onParsePageExtra, please remove.
2. Screenshot still says "Semantic" at the top, please update to theme name.
3. Description in repository (About -> Edit repository details ) and screenshot  (second line) are not in sync with description in file extension.ini. These should not differ from each other. 
4. The updated description still sounds a little to complicated. We like short/concise sentences, for example: Karlskrona is a semantic theme.

We are almost there 🙂

**Comment by pftnhr** [comment]
The tray again link now works too

**Comment by schulle4u** [comment]
Can you please restore `karlskrona.zip`? It has been deleted with your previous commit.

**Comment by schulle4u** [comment]
Thank you! 👍 Review passed and OK for merging.

**Comment by annaesvensson** [comment]
Thank you to both of you, good work.

**Pull request merged**
