### PR TITLE
Added missing strings and general revision in Italian translation

### PR DESCRIPTION
**Pull request by GiovanniSalmeri**

### CODE REVIEW

**Comment by markseu** [comment]
Looks like we worked on the same file recently. Can you have a look at the conflicts, Giovanni?

**Comment by GiovanniSalmeri** [comment]
In my file the following labels are lacking:

InstallExtensionWebsite
InstallExtensionBlog
InstallExtensionWiki

But they seem to lack also in the other language files, so my file should be in order. (Sorry if I make some mistakes with git/github, I still haven't had the time to study it enough...)

**Comment by markseu** [comment]
Sorry, I can't merge with conflicts. Can you fork the repository again and send a new pull request?

**Comment by GiovanniSalmeri** [comment]
Done, Mark. Is all OK?

**Comment by markseu** [comment]
Thank you, closing this pull request

**Pull request closed without merging**
