### PR TITLE
Add feature to set from address for contact extension

### PR DESCRIPTION
**Pull request by skrey**
I have added the option to set the from address to the contact extension. This improves the usability with sender/from restrictions on a lot of mailservers.

### CODE REVIEW

**Comment by markseuffert** [comment]
Thanks for the information, can you elaborate a little bit more on the problem. Do you know if this is caused by a local spam filter rule or by a particular mail server software? What's the address that would work with your mail server?

**Comment by skrey** [comment]
I assume that the standard mails with the noreply@hostname from address hit some spamfilter, because they never arrive (silent drop without bouncing or hitting a spam folder). If I supply a mail address with a valid domain, then the mails arrive. My first attempt was just using the admin mail address, but I then added this option to make it configurable.

**Comment by markseuffert** [comment]
I checked in my inbox which headers others are using in generated emails. It's typically a "Reply-to" address for the real person and a "From" address from the mail system where the mail originates from. Here are some examples for different "From" addresses: 

- `noreply@mojang.com` for Minecraft notifications
- `no-reply@accounts.nintendo.com` for Nintendo receipts
- `no_reply@email.apple.com` for iTunes receipts
- `notifications@github.com` for GitHub notifications
- `microsoftfamily@microsoft.com` for Microsoft notifications
- `unikum@unikum.net` for school notifications

Do you happen to know the administrator of your mail server, can you ask why they filter/drop `noreply` emails?

**Comment by skrey** [comment]
Sorry, no direct contact with the mail server admin of this domain.

noreply@ is not the problem. The hostname inserted after this is the problem. So currently I have set the from option to noreply@my-domain and this is working.

**Comment by skrey** [comment]
Correct the MTA just adds his domain, which is an internal one without a valid SPF record, so the only option I have seen was to manually set a complete from address. The simplest solution was to use the admin mail address, but I then preferred to have an option to set it individually.
Maybe it would be possible to guess a valid domain from the HTTP request, but on a shared hoster with internal domainnames, before a full domain is configured, this is very error-prone, so better set it manually.

**Comment by markseuffert** [comment]
You are right, this is the best solution. How about the following, can you do two things:

- name the new system setting `contactSiteEmail` in contact extension
- add a similar system setting `editSiteEmail` in edit extension

Then I will offer do the rest:

- update the documentation
- run the publish command

**Comment by skrey** [comment]
Rename to contactSiteEmail and addition of editSiteEmail done.

**Pull request merged**
